#!/bin/bash

while [[ $# -gt 0 ]]
do

case "$1" in
	local)
	python run.py
	shift
	;;
	serverstatus)
	request_cmd="$(curl -i -o - --silent -X GET http://localhost:5555)"
	echo "$request_cmd" |grep HTTP |awk '{print $2}'
	shift
	;;
	test)
	docker exec keystone-test python run.py &
	sleep 7
	./deploy serverstatus
	sleep 2
	docker rm -f keystone-test
	shift
	;;
	production)
	;;
	*)
	echo 'please use local, test, serverstatus or production'
	;;	
esac
shift
done
